# cf https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/#installation
# In this example, we will sample all traces and add a tag named clusterID using the
# ISTIO_META_CLUSTER_ID environment variable injected into your pod.
# Only the first 256 characters of the value will be used.
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0  # For this demo 100% of the traces should be collected
        max_path_tag_length: 256
        custom_tags:
          clusterID:
            environment:
              name: ISTIO_META_CLUSTER_ID