apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        # Pull image from local registry
      - image: localhost:5001/nodejs-app
        name: nodejs-app
        resources: {}
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: BL_HOST
          value: http://business-logic:8080
        - name: ZIPKIN_URL
          value: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
        ports:
          - name: http-port
            containerPort: 8080
            protocol: TCP
status: {}
